server:
  port: 9080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE

  config:
    import: configserver:http://localhost:9296

#Service-discovery config now added to git: chakrabortyRohit9695/spring-app-config
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
##      The &{EUREKA_SERVER_ADDRESS} is when env variable is present, if not then use the localhost url
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}