server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chakrabortyRohit9695/spring-app-config
          clone-on-start: true

#Service-discovery config now added to git: chakrabortyRohit9695/spring-app-config
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      #      The &{EUREKA_SERVER_ADDRESS} is when env variable is present, if not then use the localhost url
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}