server:
  port: 8050

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9296


#Config for connecting to service-discovery
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      #      The &{EUREKA_SERVER_ADDRESS} is when env variable is present, if not then use the localhost url
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}